routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\Catalog\CatalogController;
use App\Http\Controllers\Catalog\ProductController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\Orders\OrderController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [CatalogController::class, 'index'])->name('index.page');
Route::get('/index', [CatalogController::class, 'landingPage'])->name('index.landing_page');
Route::get('/home', [CatalogController::class, 'index'])->name('homepage');
Route::get('/category/{slug}', [CatalogController::class, 'catalogByCategory'])->name('catalogs.by_category');
Route::get('/occasion/{slug}', [CatalogController::class, 'catalogByOccasion'])->name('catalogs.by_occasion');
Route::get('/product/{slug}/{productName}', [CatalogController::class, 'productDetails'])->name('catalogs.product.details');
Route::get('/product/search', [CatalogController::class, 'searchProducts'])->name('catalogs.product.search');


Route::get('/auth/login',[LoginController::class, 'loginForm'])->name('auth.login-form');
Route::post('/auth/login',[LoginController::class, 'authenticate'])->name('auth.login');
Route::get('/auth/register',[RegisterController::class, 'registerForm'])->name('auth.register-form');
Route::post('/auth/register',[RegisterController::class, 'register'])->name('auth.register');
Route::get('/auth/reset-password',[ResetPasswordController::class, 'resetPasswordForm'])->name('auth.reset-password-form');

Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
Route::resource('manage/products', ProductController::class);
Route::resource('customer/orders', OrderController::class);

resources/views/front/home.blade.php
@extends('layouts.front_app')
@section('content')
    <!-- ========================= SECTION MAIN ========================= -->
    <section class="section-main bg padding-y-sm">
        <div class="container">
            <div class="card">
                <div class="card-body">
                    <div class="row row-sm">
                        <aside class="col-md-3">
                            <h5 class="text-uppercase">Occasions</h5>
                            <ul class="menu-category list-dots">

                                @foreach($eventTypes as $type)
                                    <li>
                                        <a href="{{route('catalogs.by_occasion',$type->slug)}}">{{$type->name}}</a>
                                    </li>
                                @endforeach

                            </ul>

                        </aside>
                        <div class="col-md-6">
                            <!-- ================= main slide ================= -->
                            <div class="owl-init slider-main owl-carousel" data-items="1" data-nav="true"
                                 data-dots="false">
                                <div class="item-slide">
                                    <img src="{{asset('images/banners/slide1.jpg')}}">
                                </div>
                                <div class="item-slide">
                                    <img src="{{asset('images/banners/slide2.jpg')}}">
                                </div>
                                <div class="item-slide">
                                    <img src="{{asset('images/banners/slide3.jpg')}}">
                                </div>
                            </div>
                            <!-- ============== main slideshow .end // ============= -->

                        </div>
                        <aside class="col-md-3">
                            <h6 class="title-bg bg-secondary">Featured Products</h6>
                            <div style="height:280px;">
                                @foreach($featuredProducts as $fp)
                                    <figure class="itemside has-bg border-bottom" style="height: 33%;">
                                        <img class="img-bg" style="max-height: 85px;"
                                             src="{{asset('storage/uploads/products/thumbnails/'.$fp->image)}}">
                                        <figcaption class="p-2">
                                            <a href="{{route('catalogs.product.details',[$fp->id,slug($fp->name)])}}">
                                                <h6 class="title">{{$fp->name}}</h6>
                                            </a>
                                            {{number_format($fp->price)}}
                                        </figcaption>
                                    </figure>
                                @endforeach
                            </div>
                        </aside>
                    </div>
                </div>
            </div>

            {{--<figure class="mt-3 banner p-3 bg-secondary">
                <div class="text-lg text-center white">Useful banner can be here</div>
            </figure>--}}
        </div>
    </section>

    @foreach($eventTypesWithProducts as $event)
        <section class="section-content padding-y-sm bg">
            <div class="container">
                <header class="section-heading heading-line">
                    <h4 class="title-section bg text-uppercase">{{$event->name}}</h4>
                </header>

                <div class="card">
                    <div class="row no-gutters">
                        <div class="col-md-3">

                            <article href="#" class="card-banner h-100 bg2">
                                <div class="card-body zoom-wrap">
                                    <h5 class="title">{{ucfirst($event->name)}}</h5>
                                    <p>{{$event->description}}</p>
                                    <a href="{{route('catalogs.by_occasion',$event->slug)}}" class="btn btn-warning">Explore</a>
                                    @if($event->icon !=null)
                                        <img src="{{asset('images/icons/'.$event->icon)}}" height="200"
                                             class="img-bg zoom-in">
                                    @endif
                                </div>
                            </article>

                        </div>
                        <div class="col-md-9">
                            @php
                                $chunkedProducts = $event->products->chunk(4);
                            @endphp
                            @foreach($chunkedProducts as $chunk)

                                <ul class="row no-gutters border-cols">
                                    @foreach($chunk as $product)
                                        <li class="col-6 col-md-3">
                                            <a href="{{route('catalogs.product.details',[$product->id,slug($product->name)])}}"
                                               class="itembox">
                                                <div class="card-body">
                                                    <p class="word-limit">{{$product->name}}</p>
                                                    @if($product->image!=null)
                                                        <img class="img-sm"
                                                             src="{{asset('storage/uploads/products/thumbnails/'.$product->image)}}"
                                                             height="100"/>
                                                    @else
                                                        <img class="img-sm" src="{{asset('images/logo-dark.png')}}"
                                                             height="60"/>
                                                    @endif
                                                </div>
                                            </a>
                                        </li>
                                    @endforeach
                                </ul>
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
        </section>
    @endforeach


    {{--<section class="section-request bg padding-y-sm">
        <div class="container">
            <header class="section-heading heading-line">
                <h4 class="title-section bg text-uppercase">Request for Quotation</h4>
            </header>

            <div class="row">
                <div class="col-md-8">
                    <figure class="card-banner banner-size-lg">
                        <figcaption class="overlay left">
                            <br>
                            <h2 style="max-width: 300px;">Big boundle or collection of featured items</h2>
                            <br>
                            <a class="btn btn-warning" href="#">Detail info » </a>
                        </figcaption>
                        <img src="images/banners/banner-request.jpg">
                    </figure>
                </div> <!-- col // -->
                <div class="col-md-4">

                    <div class="card card-body">
                        <h5 class="title py-4">One Request, Multiple Quotes.</h5>
                        <form>
                            <div class="form-group">
                                <input class="form-control" name="" type="text">
                            </div>
                            <div class="form-group">
                                <div class="input-group">
                                    <input class="form-control" name="" type="text">
                                    <span class="input-group-btn" style="border:0; width: 0;"></span>
                                    <select class="form-control">
                                        <option>Pieces</option>
                                        <option>Litres</option>
                                        <option>Tons</option>
                                        <option>Grams</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group text-muted">
                                <p>Select template type:</p>
                                <label class="form-check form-check-inline">
                                    <input class="form-check-input" type="checkbox" value="option1">
                                    <span class="form-check-label">Request price</span>
                                </label>
                                <label class="form-check form-check-inline">
                                    <input class="form-check-input" type="checkbox" value="option2">
                                    <span class="form-check-label">Request a sample</span>
                                </label>
                            </div>
                            <div class="form-group">
                                <button class="btn btn-warning">Request for quote</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>--}}

    <section class="section-request bg padding-y-sm">
        <div class="container">
            <header class="section-heading heading-line">
                <h4 class="title-section bg text-uppercase">Popular items</h4>
            </header>

            <div class="row-sm">
                @foreach($popularProducts as $product)
                    <div class="col-md-2">
                        <figure class="card card-product">
                            <div class="img-wrap"><img
                                    src="{{asset('storage/uploads/products/thumbnails/'.$product->image)}}"></div>
                            <figcaption class="info-wrap">
                                <h6 class="title "><a href="{{route('catalogs.product.details',[$product->id,slug($product->name)])}}">{{$product->name}}</a></h6>
                                <div class="price-wrap">
                                    <span class="price-new">{{number_format($product->price)}}</span>
                                    @if($product->compare_price !=null)
                                        <del class="price-old">{{number_format($product->compare_price)}}</del>
                                    @endif
                                </div>
                            </figcaption>
                        </figure>
                    </div>
                @endforeach
            </div>
        </div>
    </section>
@endsection

resources/views/front/product_details.blade.php
@extends('layouts.front_app')
@section('content')
    <section class="section-content my-3">
        <div class="container">
            <nav class="mb-3">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{route('homepage')}}">Home</a></li>
                    @if($product->category!=null)
                        <li class="breadcrumb-item"><a
                                href="{{route('catalogs.by_category',$product->category->slug)}}">{{$product->category->name}}</a>
                        </li>
                    @endif
                    <li class="breadcrumb-item active" aria-current="page">{{ucfirst($product->name)}}</li>
                </ol>
            </nav>

            <div class="row">
                <div class="col-xl-9 col-md-9 col-sm-12">

                    <main class="card">
                        <div class="row no-gutters">
                            <aside class="col-sm-6 border-right">
                                <article class="gallery-wrap">
                                    <div class="img-big-wrap">
                                        <div>
                                            @if($product->image !=null)
                                                <img src="{{asset('storage/uploads/products/'.$product->image)}}"/>
                                            @endif
                                        </div>
                                        {{-- <div class="img-small-wrap">
                                             @if($product->image !=null)
                                                 <img class="item-gallery"
                                                      src="{{asset('storage/uploads/products/'.$product->image)}}"/>
                                                 <img class="item-gallery"
                                                      src="{{asset('storage/uploads/products/'.$product->image)}}"/>
                                             @endif
                                         </div>--}}
                                    </div>
                                </article>
                            </aside>
                            <aside class="col-sm-6">
                                <article class="card-body">
                                    <h3 class="title mb-3">{{ucfirst($product->name)}}</h3>

                                    <div class="mb-3">
                                        <var class="price h3 text-warning">
                                            <span class="currency">TZS</span><span
                                                class="num"> {{number_format($product->price)}}</span>
                                        </var>
                                    </div>
                                    <dl>
                                        <dt>Description</dt>
                                        <dd><p>{{$product->description}}</p></dd>
                                    </dl>
                                    <dl class="row">
                                        <dt class="col-sm-3">Model#</dt>
                                        <dd class="col-sm-9">12345611</dd>

                                        <dt class="col-sm-3">Color</dt>
                                        <dd class="col-sm-9">Black and white</dd>

                                        <dt class="col-sm-3">Delivery</dt>
                                        <dd class="col-sm-9">Russia, USA, and Europe</dd>
                                    </dl>
                                    <div class="rating-wrap">

                                        <ul class="rating-stars">
                                            <li style="width:80%" class="stars-active">
                                                <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                            </li>
                                            <li>
                                                <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                            </li>
                                        </ul>
                                        <div class="label-rating">132 reviews</div>
                                        <div class="label-rating">154 orders</div>
                                    </div>
                                    <hr>
                                    <div class="row">
                                        <div class="col-sm-5">
                                            <dl class="dlist-inline">
                                                <dt>Quantity:</dt>
                                                <dd>
                                                    <select class="form-control form-control-sm" style="width:70px;">
                                                        <option> 1</option>
                                                        <option> 2</option>
                                                        <option> 3</option>
                                                    </select>
                                                </dd>
                                            </dl>  <!-- item-property .// -->
                                        </div>
                                        <div class="col-sm-7">
                                            <dl class="dlist-inline">
                                                <dt>Size:</dt>
                                                <dd>
                                                    <label class="form-check form-check-inline">
                                                        <input class="form-check-input" name="inlineRadioOptions"
                                                               id="inlineRadio2" value="option2" type="radio">
                                                        <span class="form-check-label">SM</span>
                                                    </label>
                                                    <label class="form-check form-check-inline">
                                                        <input class="form-check-input" name="inlineRadioOptions"
                                                               id="inlineRadio2" value="option2" type="radio">
                                                        <span class="form-check-label">MD</span>
                                                    </label>
                                                    <label class="form-check form-check-inline">
                                                        <input class="form-check-input" name="inlineRadioOptions"
                                                               id="inlineRadio2" value="option2" type="radio">
                                                        <span class="form-check-label">XXL</span>
                                                    </label>
                                                </dd>
                                            </dl>
                                        </div>
                                    </div>
                                    <hr>
                                    <button type="button" class="btn btn-outline-success"
                                            data-bs-toggle="modal" data-target="#customizeProductModal">
                                        {{__('Customize')}}</button>
                                </article>
                            </aside>
                        </div>
                    </main>

                    <article class="card mt-3">
                        <div class="card-body">
                            <h4>Detail overview</h4>
                            {!! $product->description !!}
                        </div>
                    </article>
                </div>
                <aside class="col-xl-3 col-md-3 col-sm-12">
                    <div class="card">
                        <div class="card-header">
                            Related items
                        </div>
                        <div class="card-body small">
                            list here
                        </div>
                    </div>
                </aside>
            </div>
        </div>


        <div class="modal fade" id="customizeProductModal" tabindex="-1" aria-labelledby="customizeProductModalLabel"
             aria-hidden="true">

        <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Customize - {{$product->name}}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                    <form method="post" enctype="multipart/form-data" id="customizeProductForm">
                        @csrf
                        <input type="hidden" name="productId" value="{{$product->id}}"/>
                        <div class="modal-body">
                            <div class="mb-3">
                                <label for="" class="form-label">Names</label>
                                <input type="text" class="form-control" name="name"
                                       placeholder="John Doe">
                            </div>

                            <div class="mb-3">
                                <label for="" class="form-label">{{__('Message')}}</label>
                                <textarea class="form-control" name="message" rows="2"></textarea>
                            </div>

                            <div class="mb-3">
                                <label for="" class="form-label">{{__('Additional message')}}</label>
                                <textarea class="form-control" name="additionalMessage" rows="1"></textarea>
                            </div>

                            <div class="mb-3">
                                <label for="" class="form-label">{{__('Comments')}}</label>
                                <textarea class="form-control" name="comment" rows="1"></textarea>
                            </div>

                            <div class="mb-3">
                                <label for="" class="form-label">{{__('Custom photo')}}</label>
                                <input type="file" class="form-control" name="customProductPhoto"/>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-light"
                                    data-dismiss="modal">{{__('forms.btn_close')}}</button>
                            <button type="submit" class="btn btn-primary">{{__('forms.btn_save_changes')}}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <script type="text/javascript">

        $(document).ready(function () {

            $('#customizeProductForm').on('submit', function (event) {
                event.preventDefault();

                const formData = new FormData($(this)[0]);

                $.ajax({
                        url: '{{route('orders.store')}}',
                        type: 'post',
                        method: 'post',
                        data: formData,
                        contentType: false,
                        processData: false,
                        success: (data) => {
                            console.log(data);
                        },
                        beforeSend: () => {
                            console.log('Before send called')
                        }
                    }
                );
            })
            ;
        });
    </script>
@endsection