routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\Catalog\CatalogController;
use App\Http\Controllers\Catalog\ProductController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\Orders\OrderController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [CatalogController::class, 'index'])->name('index.page');
Route::get('/index', [CatalogController::class, 'landingPage'])->name('index.landing_page');
Route::get('/home', [CatalogController::class, 'index'])->name('homepage');
Route::get('/category/{slug}', [CatalogController::class, 'catalogByCategory'])->name('catalogs.by_category');
Route::get('/occasion/{slug}', [CatalogController::class, 'catalogByOccasion'])->name('catalogs.by_occasion');
Route::get('/product/{slug}/{productName}', [CatalogController::class, 'productDetails'])->name('catalogs.product.details');
Route::get('/product/search', [CatalogController::class, 'searchProducts'])->name('catalogs.product.search');


Route::get('/auth/login',[LoginController::class, 'loginForm'])->name('auth.login-form');
Route::post('/auth/login',[LoginController::class, 'authenticate'])->name('auth.login');
Route::get('/auth/register',[RegisterController::class, 'registerForm'])->name('auth.register-form');
Route::post('/auth/register',[RegisterController::class, 'register'])->name('auth.register');
Route::get('/auth/reset-password',[ResetPasswordController::class, 'resetPasswordForm'])->name('auth.reset-password-form');

Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
Route::resource('manage/products', ProductController::class);
Route::resource('customer/orders', OrderController::class);

app/Models/Catalog/Product.php
<?php

namespace App\Models\Catalog;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $with = ['category', 'productType', 'occasion'];

    public function productCategory()
    {
        return $this->belongsTo(ProductCategory::class, 'product_category_id');
    }

    public function category()
    {
        return $this->productCategory();
    }

    public function productType()
    {
        return $this->belongsTo(ProductType::class, 'product_type_id');
    }

    public function occasion()
    {
        return $this->belongsTo(EventType::class, 'event_type_id');
    }

    public function eventType()
    {
        return $this->occasion();
    }

    public function scopeActive($q)
    {
        return $q->where('status', 1);
    }
}

app/Models/Catalog/ProductType.php
<?php

namespace App\Models\Catalog;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ProductType extends Model
{
    use HasFactory;

    public function scopeActive($q)
    {
        return $q->where('status', 1);
    }
}

app/Http/Controllers/Catalog/ProductController.php
<?php

namespace App\Http\Controllers\Catalog;

use App\Http\Controllers\Controller;
use App\Models\Catalog\EventType;
use App\Models\Catalog\Product;
use App\Models\Catalog\ProductCategory;
use App\Models\Catalog\ProductType;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;
use Intervention\Image\Facades\Image;
use function PHPUnit\Framework\exactly;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $products = Product::orderBy('updated_at', 'DESC')->paginate();
        return view('admin.products.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('admin.products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  Product  $product
     * @return Response
     */
    public function show(Product $product)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Product  $product
     * @return Response
     */
    public function edit(Product $product)
    {
        $categories = ProductCategory::all();
        $productTypes = ProductType::all();
        $eventTypes = EventType::all();

        return view('admin.products.edit', compact('product', 'categories', 'productTypes', 'eventTypes'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  Product  $product
     * @return Response
     */
    public function update(Request $request, Product $product)
    {
        $request->validate(
            [
                'name'            => 'required',
                'barcode'         => 'required|unique:products,barcode,'.$product->id,
                'cost'            => 'required|min:50|numeric',
                'price'           => 'required|min:50|numeric',
                'description'     => 'nullable',
                'productType'     => 'nullable',
                'productCategory' => 'required',
                'eventType'       => 'nullable',
                'status'          => 'required',
                'productPhoto'    => 'nullable|image|mimes:jpeg,png,jpg,gif,svg|max:1024',
            ]
        );

        DB::beginTransaction();
        try {
            $imageName = $this->saveProductPhoto($request);

            $newDetails = [
                'name'                => $request->name,
                'cost'                => $request->cost,
                'price'               => $request->price,
                'barcode'             => $request->barcode,
                'event_type_id'       => $request->eventType,
                'product_category_id' => $request->productCategory,
                'status'              => $request->status
            ];

            if ($request->productType != null) {
                $newDetails['product_type_id'] = $request->productType;
            }

            if ($request->productCategory != null) {
                $newDetails['product_category_id'] = $request->productCategory;
            }

            if ($imageName != null) {
                $newDetails['image'] = $imageName;
            }
            $previousProductImage = $product->image;

            $updateResult = Product::where(['id' => $product->id])->update($newDetails);
            if ($updateResult) {
                if ($imageName != null && $previousProductImage != null) {
                    $this->deleteOlderImage($previousProductImage);
                }
            }

            DB::commit();
            $this->messages['success'] = 'Product was successfully updated';
            return redirect(route('products.index'))->with($this->messages);
        } catch (Exception $exception) {
            DB::rollBack();
            logException($exception);
            $this->messages['failure'] = 'Failed to update product '.$exception->getMessage();
            return redirect()->back()->withInput()->with($this->messages);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Product  $product
     * @return Response
     */
    public function destroy(Product $product)
    {
        //
    }

    private function saveProductPhoto(Request $request)
    {
        $imageName = null;
        try {
            if ($request->productPhoto != null) {
                $uploadDir = storage_path('app/public/uploads/products');
                $thumbnailsDir = $uploadDir.DIRECTORY_SEPARATOR.'thumbnails';
                if (!File::isDirectory($thumbnailsDir)) {
                    File::makeDirectory($uploadDir, 0777, true, true);
                    File::makeDirectory($thumbnailsDir, 0777, true, true);
                }

                $imageName = str_replace('-', '', Str::uuid()->toString()).'.'.$request->productPhoto->extension();
                $image = $request->file('productPhoto');

                $img = $thumbnail = Image::make($image->path());
                //$img->opacity(0);
                $img->resize(500, null, function ($const) {
                    $const->aspectRatio();
                })->save($uploadDir.DIRECTORY_SEPARATOR.$imageName);

                $thumbnail->resize(400,null, function ($const) {
                    $const->aspectRatio();
                })->save($thumbnailsDir.DIRECTORY_SEPARATOR.$imageName);
            }
        } catch (Exception $exception) {
            logException($exception);
        }
        return $imageName;
    }

    private function deleteOlderImage(string $filename)
    {
        try {
            $image = storage_path('app/public/uploads/products').DIRECTORY_SEPARATOR.$filename;
            $thumbnail = $image.DIRECTORY_SEPARATOR.'thumbnails'.DIRECTORY_SEPARATOR.$filename;
            if (File::exists($image)) {
                File::delete($image);
                @File::delete($thumbnail);
            }
        } catch (Exception $exception) {
            logException($exception);
        }
    }
}

resources/views/admin/products/create.blade.php
@extends('layouts.employee')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h3 class="text-2xl text-gray-900 font-semibold my-2"><i
                        class="fa fa-edit text-primary mr-2"></i>{{__('forms.title_product_details')}}
                </h3>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <form action="{{route('products.store')}}" method="post" class="bg-white p-3"
                      accept-charset="UTF-8" id="createProductForm" enctype="multipart/form-data">
                    @csrf
                    <div class="row">
                        <div class="col-xl-8 col-md-8 col-sm-12">
                            <div class='row'>
                                <div class='col-12 mb-2'>
                                    <label class="col-form-label" for='title'>{{__('forms.label_product_name')}}</label>
                                    <input
                                        class="form-control border @error('title') border-danger @enderror "
                                        id='title' type='text' placeholder='{{__('forms.placeholder_product_name')}}'
                                        name="title" value="{{old('title')}}">

                                    @error('title')
                                    <div class=" text-danger text-sm p-2">{{$errors->first('title')}}</div>
                                    @enderror
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6 col-sm-12 mb-2">
                                    <label class="col-form-label" for='price'>{{__('forms.label_price')}}</label>
                                    <input type="number" name="price" id="price"
                                           placeholder="{{__('forms.placeholder_price')}}"
                                           value="{{old('price')}}"
                                           class="form-control border  @error('price') border-danger @enderror">

                                    @error('price')
                                    <div class=" text-danger text-sm p-2">{{$errors->first('price')}}</div>
                                    @enderror
                                </div>
                                <div class="col-md-6 col-sm-12 mb-2">
                                    <label class="col-form-label" for='cost'>{{__('forms.label_unit_cost')}}</label>
                                    <input type="number" name="cost" id="cost"
                                           placeholder="{{__('forms.placeholder_unit_cost')}}"
                                           value="{{old('cost')}}"
                                           class="form-control border  @error('cost') border-danger @enderror">
                                    @error('cost')
                                    <div class=" text-danger text-sm p-2">{{$errors->first('cost')}}</div>
                                    @enderror
                                </div>
                            </div>

                            <div class="row mb-2">
                                <div class='col-md-6 col-sm-12'>
                                    <label class="col-form-label"
                                           for='isbn'>{{__('forms.label_isbn')}}</label>
                                    <input type="text" name="barcode" id="barcode"
                                           placeholder="{{__('forms.placeholder_isbn')}}"
                                           value="{{old('barcode')}}"
                                           class="form-control border  @error('isbn') border-danger @enderror">

                                    @error('barcode')
                                    <div class=" text-danger text-sm p-2">{{$errors->first('barcode')}}</div>
                                    @enderror
                                </div>
                                <div class='col-md-6 col-sm-12 '>
                                    <label class="col-form-label"
                                           for='originCountry'>{{__('forms.label_from_country')}}</label>

                                    <select name="originCountry" id="originCountry"
                                            class="form-control border @error('originCountry') border-danger @enderror">
                                        <option value="">{{__('forms.select_country')}}</option>
                                        @foreach($countries as $country)
                                            <option value="{{$country->id}}"
                                                    @if (old('country') == $country->id) selected @endif>
                                                {{$country->name}}
                                            </option>
                                        @endforeach
                                    </select>
                                    @error('originCountry')
                                    <div class="text-danger text-sm p-2">{{$errors->first('originCountry')}}</div>
                                    @enderror
                                </div>
                            </div>

                            <div class="row">
                                <div class='col-md-6 col-sm-12'>
                                    <label class="col-form-label"
                                           for='productType'>{{__('forms.label_product_type')}}</label>

                                    <select name="productType" id="productType"
                                            class="form-control border  @error('productType') border-danger @enderror">
                                        <option value="">{{__('forms.select_product_type')}}</option>
                                        @foreach($productTypes as $type)
                                            <option value="{{$type->id}}"
                                                    @if (old('productType') == $type->id)
                                                    selected @endif>{{$type->name}}</option>
                                        @endforeach
                                    </select>
                                    @error('productType')
                                    <div
                                        class=" text-danger text-sm p-2">{{$errors->first('productType')}}</div>
                                    @enderror
                                </div>
                                <div class='col-md-6 col-sm-12'>
                                    <label class="col-form-label" for='status'>{{__('forms.label_status')}}</label>

                                    <select name="status" id="status"
                                            class="form-control border @error('status') border-danger @enderror">
                                        <option value="">{{__('forms.select_publish_status')}}</option>
                                        <option value="1"
                                                @if (old('status') == 1) selected @endif>{{__('contents.status_published')}}</option>
                                        <option value="0"
                                                @if (old('status') == 0) selected @endif>{{__('contents.status_unpublished')}}</option>
                                    </select>
                                    @error('status')
                                    <div class="text-danger text-sm p-2">{{$errors->first('status')}}</div>
                                    @enderror
                                </div>
                            </div>

                            <div class='row'>
                                <div class='col-12'>
                                    <label class='col-form-label'>{{__('forms.label_description')}}</label>
                                    <textarea cols="10" rows="3" placeholder="{{__('forms.placeholder_product_desc')}}"
                                              class='form-control border @error(' description') border-danger @enderror'
                                              name="description">{{old('description')}}</textarea>
                                    @error('description')
                                    <div class="text-danger text-sm p-2">{{$errors->first('description')}}</div>
                                    @enderror
                                </div>
                            </div>
                        </div>

                        <div class="col-xl-4 col-md-4 col-sm-12">
                            <div class="row">
                                <div class='col-12'>
                                    <label for='category'>{{__('forms.label_product_category')}}</label>
                                    <select name="category" id="category"
                                            class="form-control border p-3   @error('category') border-danger @enderror">
                                        <option value="">{{__('forms.select_product_category')}}</option>
                                        @foreach($categories as $category)
                                            <option value="{{$category->id}}"
                                                    @if (old('category') == $category->id) selected @endif>{{$category->name}}
                                            </option>

                                        @endforeach
                                    </select>
                                    @error('category')
                                    <div class=" text-danger text-sm p-2">{{$errors->first('category')}}</div>
                                    @enderror
                                </div>

                                <div class='col-12 mt-4'>
                                    <div class="row">
                                        <div class="col-12">
                                            <label for='authorsDropdown'
                                                   class="float-left d-inline-block">{{__('forms.label_author')}}</label>

                                            <button type="button" class="btn btn-link pull-right  d-inline-block"
                                                    id="btnShowAddAuthorModal">{{__('forms.btn_add_new_author')}}</button>
                                        </div>
                                    </div>

                                    <select name="author" id="authorsDropdown"
                                            class="form-control border p-3   @error('author') border-danger @enderror">
                                        <option value="">{{__('forms.select_author')}}</option>
                                        @foreach($authors as $author)
                                            <option value="{{$author->id}}"
                                                    @if (old('author') == $author->id) selected @endif>{{$author->name}}
                                            </option>
                                        @endforeach
                                    </select>
                                    @error('author')
                                    <div class=" text-danger text-sm p-2">{{$errors->first('author')}}</div>
                                    @enderror
                                </div>

                                <div class='col-12 mt-4'>
                                    <label for='publishersDropdown'>{{__('forms.label_publisher')}}
                                        <span class="float-end pull-right">
                                        <button type="button" class="btn btn-link" id="btnShowAddPublisherModal">
                                            {{__('forms.btn_add_new_publisher')}}</button></span></label>

                                    <select name="publisher" id="publishersDropdown"
                                            class="form-control border  @error('publisher') border-danger @enderror">
                                        <option value="">{{__('forms.select_book_publisher')}}</option>
                                        @foreach($publishers as $publisher)
                                            <option value="{{$publisher->id}}"
                                                    @if (old('publisher') == $publisher->id) selected @endif>{{$publisher->name}}
                                            </option>
                                        @endforeach
                                    </select>
                                    @error('publisher')
                                    <div class=" text-danger text-sm p-2">{{$errors->first('publisher')}}</div>
                                    @enderror
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-12">
                            <button class="btn btn-primary text-white" type="submit">{{__("forms.btn_save_changes")}}
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/products/index.blade.php
@extends('layouts.admin')
@section('content')

    <div class="row mt-4">
        <div class="col-12">
            <h4 class="mb-1 h4">Products list</h4>
            <table class="table table-responsive-lg table-borderless table-striped">
                <tr>
                    <td>Photo</td>
                    <td>Product name</td>
                    <td>Category</td>
                    <td>Type</td>
                    <td>Occasion</td>
                    <td>Price</td>
                    <td></td>
                </tr>
                @foreach($products as $product)

                    <tr>
                        <td>
                            @if($product->image!=null)
                                <img src="{{asset('storage/uploads/products/thumbnails/'.$product->image)}}"
                                     height="60"/>
                            @else
                                <img src="{{asset('images/logo-dark.png')}}" height="60"/>
                            @endif
                        </td>
                        <td><a href="{{route('catalogs.product.details',[$product->id,slug($product->name)])}}"
                               target="_blank">{{$product->name}}</a></td>
                        <td>@if($product->productCategory!=null){{$product->productCategory->name}}@endif</td>
                        <td>@if($product->productType!=null){{$product->productType->name}}@endif</td>
                        <td>@if($product->occasion !=null){{$product->occasion->name}}@endif</td>
                        <td>{{number_format($product->price)}}TZS</td>
                        <td><a href="{{route('products.edit',$product)}}">Edit</a></td>
                    </tr>

                @endforeach
            </table>

        </div>
    </div>

@endsection