routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\Catalog\CatalogController;
use App\Http\Controllers\Catalog\ProductController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\Orders\OrderController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [CatalogController::class, 'index'])->name('index.page');
Route::get('/index', [CatalogController::class, 'landingPage'])->name('index.landing_page');
Route::get('/home', [CatalogController::class, 'index'])->name('homepage');
Route::get('/category/{slug}', [CatalogController::class, 'catalogByCategory'])->name('catalogs.by_category');
Route::get('/occasion/{slug}', [CatalogController::class, 'catalogByOccasion'])->name('catalogs.by_occasion');
Route::get('/product/{slug}/{productName}', [CatalogController::class, 'productDetails'])->name('catalogs.product.details');
Route::get('/product/search', [CatalogController::class, 'searchProducts'])->name('catalogs.product.search');


Route::get('/auth/login',[LoginController::class, 'loginForm'])->name('auth.login-form');
Route::post('/auth/login',[LoginController::class, 'authenticate'])->name('auth.login');
Route::get('/auth/register',[RegisterController::class, 'registerForm'])->name('auth.register-form');
Route::post('/auth/register',[RegisterController::class, 'register'])->name('auth.register');
Route::get('/auth/reset-password',[ResetPasswordController::class, 'resetPasswordForm'])->name('auth.reset-password-form');

Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
Route::resource('manage/products', ProductController::class);
Route::resource('customer/orders', OrderController::class);

resources/views/layouts/admin.blade.php
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="Bootstrap-ecommerce by Vosidiy">

    <title>{{$title ?? 'Kwanza prints - Home of unique customised gifts for our loved ones, awards, plaques, Signs'}}</title>
    <script src="{{asset('js/jquery-2.0.0.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('js/bootstrap.bundle.min.js?v=1.01')}}" type="text/javascript"></script>
    <link href="{{asset('css/bootstrap-custom.css')}}" rel="stylesheet" type="text/css"/>
</head>
<body>

<div class="container">

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{{route('dashboard')}}">Dashboard</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{{route('products.index')}}">Manage products</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{route('orders.index')}}">{{__('Customer Orders')}}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{route('index.page')}}" target="_blank">View site</a>
                </li>
                {{--<li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        Dropdown link
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>--}}
            </ul>
        </div>
    </nav>

</div>

<div class="container">
    @yield('content')
</div>

<div class="container">
    <a href="">&nbsp; {{date('Y')}} Kwanzaprints</a>
</div>

</body>
</html>

resources/views/layouts/front_app.blade.php
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="Bootstrap-ecommerce by Vosidiy">

    <title>{{$title ?? 'Kwanza prints - Home of unique customised gifts for our loved ones, awards, plaques, Signs'}}</title>

    <link rel="shortcut icon" type="image/x-icon" href="{{asset('images/favicon.ico')}}">

    <link href="{{asset('css/bootstrap.min.css')}}" rel="stylesheet" type="text/css"/>
    <link href="{{asset(mix('css/app.css'))}}" rel="stylesheet" type="text/css"/>
    <script src="{{asset('js/bootstrap.min.js')}}" type="text/javascript"></script>

    <script src="https://kit.fontawesome.com/feff13e77c.js" crossorigin="anonymous"></script>
</head>
<body>

<header>
    <nav class="navbar navbar-expand-md navbar-light fixed-top bg-light">
        <div class="container">
            <a class="navbar-brand" href="{{route('index.page')}}">Kwanza Prints</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{route('index.landing_page')}}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('products.index')}}">Shop</a>
                    </li>
                </ul>

                <ul class="navbar-nav me-auto mb-2 mb-md-0 d-flex align-items-end align-content-end">
                    <li class="nav-item">
                        <a class="nav-link" href="#"><i class="fas fa-cart-shopping text-orange"></i> My Order</a>
                    </li>
                </ul>

                <form class="d-flex" method="get" action="{{route('catalogs.product.search')}}">
                    <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
</header>


@yield('content')

<!-- FOOTER -->
<div class="container-fluid footer py-4 mt-5 text-white">
    <footer class="container">
        <div class="row">
            <aside class="col-sm-3 col-md-3 white">
                <h5 class="title">Customer Services</h5>
                <ul class="list-unstyled">
                    <li><a href="#">Help center</a></li>
                    <li><a href="#">Money refund</a></li>
                    <li><a href="#">Terms and Policy</a></li>
                    <li><a href="#">Open dispute</a></li>
                </ul>
            </aside>
            <aside class="col-sm-3  col-md-3 white">
                <h5 class="title">My Account</h5>
                <ul class="list-unstyled">
                    <li><a href="{{route('auth.login')}}"> User Login </a></li>
                    <li><a href="#"> User register </a></li>
                    <li><a href="#"> Account Setting </a></li>
                    <li><a href="#"> My Orders </a></li>
                    <li><a href="#"> My Wishlist </a></li>
                </ul>
            </aside>
            <aside class="col-sm-3  col-md-3 white">
                <h5 class="title">About</h5>
                <ul class="list-unstyled">
                    <li><a href="#"> Our history </a></li>
                    <li><a href="#"> How to buy </a></li>
                    <li><a href="#"> Delivery and payment </a></li>
                    <li><a href="#"> Advertice </a></li>
                    <li><a href="#"> Partnership </a></li>
                </ul>
            </aside>
            <aside class="col-sm-3">
                <article class="white">
                    <h5 class="title">Contacts</h5>
                    <p>
                        <strong>Phone: </strong> +255 659 999 917 <br>
                    </p>

                    <div class="btn-group white">

                        <a class="btn btn-youtube text-orange" title="WhatsApp" target="_blank"
                           href="https://wa.me/255659999917?text={{urlencode('Hello Kwanzaprints, I am inquiring for ')}}">
                            <i class="fab fa-whatsapp fa-fw fa-2x"></i></a>

                        <a class="btn btn-instagram text-orange" title="Instagram" target="_blank"
                           href="https://www.instagram.com/kwanzaprints/"><i
                                class="fab fa-instagram fa-fw fa-2x text-orange"></i></a>

                        <a class="btn btn-facebook text-orange" title="Facebook" target="_blank"
                           href="https://www.facebook.com/KwanzaPrints"><i
                                class="fab fa-facebook-f fa-fw fa-2x text-orange"></i></a>


                        <a class="btn btn-twitter text-orange" title="Twitter" target="_blank" href="#"><i
                                class="fab fa-twitter fa-fw fa-2x"></i></a>
                    </div>
                </article>

                {{--<div class="col-12">
                    <ul class="list-inline">
                        <li class="list-inline-item"><i class="fa fa-whatsapp fa-1x text-orange"></i></li>
                        <li class="list-inline-item"><i class="fa fa-facebook fa-1x text-orange"></i></li>
                        <li class="list-inline-item"><i class="fa fa-instagram fa-1x text-orange"></i></li>
                        <li class="list-inline-item"><i class="fa fa-twitter fa-1x text-orange"></i></li>
                    </ul>
                </div>--}}
            </aside>
        </div>

        <div class="row">
            <div class="col-12">
                <p class="float-end"><a href="#">Back to top</a></p>
                <p> {{date('Y')}} &copy; KwanzaPrints &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a>
                </p>
            </div>
        </div>
    </footer>
</div>
</body>
</html>

resources/views/layouts/slider.blade.php
<!-- Begin Slider With Category Menu Area -->
<div class="slider-with-banner">
    <div class="container">
        <div class="row">
            <!-- Begin Category Menu Area -->
            <div class="col-lg-3">
                <!--Category Menu Start-->
                <div class="category-menu">
                    <div class="category-heading">
                        <h2 class="categories-toggle"><span>categories</span></h2>
                    </div>
                    <div id="cate-toggle" class="category-menu-list">
                        <ul>
                            <li class="right-menu"><a href="shop-left-sidebar.html">Laptops</a>
                                <ul class="cat-mega-menu">
                                    <li class="right-menu cat-mega-title">
                                        <a href="shop-left-sidebar.html">Prime Video</a>
                                        <ul>
                                            <li><a href="#">All Videos</a></li>
                                            <li><a href="#">Blouses</a></li>
                                            <li><a href="#">Evening Dresses</a></li>
                                            <li><a href="#">Summer Dresses</a></li>
                                            <li><a href="#">T-shirts</a></li>
                                            <li><a href="#">Rent or Buy</a></li>
                                            <li><a href="#">Your Watchlist</a></li>
                                            <li><a href="#">Watch Anywhere</a></li>
                                            <li><a href="#">Getting Started</a></li>
                                        </ul>
                                    </li>
                                    <li class="right-menu cat-mega-title">
                                        <a href="shop-left-sidebar.html">Computers</a>
                                        <ul>
                                            <li><a href="#">More to Explore</a></li>
                                            <li><a href="#">TV & Video</a></li>
                                            <li><a href="#">Audio & Theater</a></li>
                                            <li><a href="#">Camera, Photo</a></li>
                                            <li><a href="#">Cell Phones</a></li>
                                            <li><a href="#">Headphones</a></li>
                                            <li><a href="#">Video Games</a></li>
                                            <li><a href="#">Wireless Speakers</a></li>
                                        </ul>
                                    </li>
                                    <li class="right-menu cat-mega-title">
                                        <a href="shop-left-sidebar.html">Electronics</a>
                                        <ul>
                                            <li><a href="#">Amazon Home</a></li>
                                            <li><a href="#">Kitchen & Dining</a></li>
                                            <li><a href="#">Furniture</a></li>
                                            <li><a href="#">Bed & Bath</a></li>
                                            <li><a href="#">Appliances</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                            <li class="right-menu"><a href="shop-left-sidebar.html">TV & Audio</a>
                                <ul class="cat-mega-menu">
                                    <li class="right-menu cat-mega-title">
                                        <a href="shop-left-sidebar.html">Chamcham</a>
                                        <ul>
                                            <li><a href="#">Office</a></li>
                                            <li><a href="#">Gaming</a></li>
                                            <li><a href="#">Chromebook</a></li>
                                            <li><a href="#">Refurbished</a></li>
                                            <li><a href="#">Touchscreen</a></li>
                                            <li><a href="#">Ultrabooks</a></li>
                                            <li><a href="#">Netbook</a></li>
                                        </ul>
                                    </li>
                                    <li class="right-menu cat-mega-title">
                                        <a href="shop-left-sidebar.html">Meito</a>
                                        <ul>
                                            <li><a href="#">Hard Drives</a></li>
                                            <li><a href="#">Graphic Cards</a></li>
                                            <li><a href="#">Processors (CPU)</a></li>
                                            <li><a href="#">Memory</a></li>
                                            <li><a href="#">Motherboards</a></li>
                                            <li><a href="#">Fans & Cooling</a></li>
                                            <li><a href="#">CD/DVD Drives</a></li>
                                        </ul>
                                    </li>
                                    <li class="right-menu cat-mega-title">
                                        <a href="shop-left-sidebar.html">Sony Bravia</a>
                                        <ul>
                                            <li><a href="#">Sound Cards</a></li>
                                            <li><a href="#">Cases & Towers</a></li>
                                            <li><a href="#">Casual Dresses</a></li>
                                            <li><a href="#">Evening Dresses</a></li>
                                            <li><a href="#">T-shirts</a></li>
                                            <li><a href="#">Tops</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                            <li class="right-menu"><a href="shop-left-sidebar.html">Smartphone</a>
                                <ul class="cat-mega-menu cat-mega-menu-2">
                                    <li class="right-menu cat-mega-title">
                                        <a href="shop-left-sidebar.html">Camera Accessories</a>
                                        <ul>
                                            <li><a href="#">Octa Core</a></li>
                                            <li><a href="#">Quad Core</a></li>
                                            <li><a href="#">Dual Core</a></li>
                                            <li><a href="#">7.0 Screen</a></li>
                                            <li><a href="#">9.0 Screen</a></li>
                                            <li><a href="#">Bags & Cases</a></li>
                                        </ul>
                                    </li>
                                    <li class="right-menu cat-mega-title">
                                        <a href="shop-left-sidebar.html">XailStation</a>
                                        <ul>
                                            <li><a href="#">Batteries</a></li>
                                            <li><a href="#">Microphones</a></li>
                                            <li><a href="#">Stabilizers</a></li>
                                            <li><a href="#">Video Tapes</a></li>
                                            <li><a href="#">Memory Card Readers</a></li>
                                            <li><a href="#">Tripods</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                            <li><a href="#">Cameras</a></li>
                            <li><a href="#">Headphone</a></li>
                            <li><a href="#">Smartwatch</a></li>
                            <li><a href="#">Out Door Room</a></li>
                            <li><a href="#">Chamcham</a></li>
                            <li class="rx-child"><a href="#">Mobile & Tablets</a></li>
                            <li class="rx-child"><a href="#">Accessories</a></li>
                            <li class="rx-parent">
                                <a class="rx-default">More Categories</a>
                                <a class="rx-show">Less Categories</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <!--Category Menu End-->
            </div>
            <!-- Category Menu Area End Here -->
            <!-- Begin Slider Area -->
            <div class="col-lg-9">
                <div class="slider-area pt-sm-30 pt-xs-30">
                    <div class="slider-active owl-carousel">
                        <!-- Begin Single Slide Area -->
                        <div class="single-slide align-center-left animation-style-02 bg-4">
                            <div class="slider-progress"></div>
                            <div class="slider-content">
                                <h5>Sale Offer <span>-20% Off</span> This Week</h5>
                                <h2>Chamcham Galaxy S9 | S9+</h2>
                                <h3>Starting at <span>$589.00</span></h3>
                                <div class="default-btn slide-btn">
                                    <a class="links" href="shop-left-sidebar.html">Shopping Now</a>
                                </div>
                            </div>
                        </div>
                        <!-- Single Slide Area End Here -->
                        <!-- Begin Single Slide Area -->
                        <div class="single-slide align-center-left animation-style-01 bg-5">
                            <div class="slider-progress"></div>
                            <div class="slider-content">
                                <h5>Sale Offer <span>Black Friday</span> This Week</h5>
                                <h2>Work Desk Surface Studio 2018</h2>
                                <h3>Starting at <span>$1599.00</span></h3>
                                <div class="default-btn slide-btn">
                                    <a class="links" href="shop-left-sidebar.html">Shopping Now</a>
                                </div>
                            </div>
                        </div>
                        <!-- Single Slide Area End Here -->
                        <!-- Begin Single Slide Area -->
                        <div class="single-slide align-center-left animation-style-02 bg-6">
                            <div class="slider-progress"></div>
                            <div class="slider-content">
                                <h5>Sale Offer <span>-10% Off</span> This Week</h5>
                                <h2>Phantom 4 Pro+ Obsidian</h2>
                                <h3>Starting at <span>$809.00</span></h3>
                                <div class="default-btn slide-btn">
                                    <a class="links" href="shop-left-sidebar.html">Shopping Now</a>
                                </div>
                            </div>
                        </div>
                        <!-- Single Slide Area End Here -->
                    </div>
                </div>
            </div>
            <!-- Slider Area End Here -->
        </div>
    </div>
</div>
<!-- Slider With Category Menu Area End Here -->